---
layout: cv
title: Estime Kongolo's CV
---
# Estime Kongolo
Data Science Student, Teaching Assistant, Technology Specialist.

<div id="webaddress">
<a href="estimemusema@icloud.com">estimemusema@icloud.com</a>
| <a href="https://www.linkedin.com/in/estimemusemakongolo/">My linkedin page</a>
</div>


## Currently

Pursuing a Bachelors Degree in Data Science 

### Specialized in

R and Python programming


### Research interests

Technology and Machine learning


## Education

`2008-2013`
__Oude Molen Technical High School, Cape Town SA__

`2023 - Now`
__Brigham Young University-Idaho, Rexburg__



## Awards

`2012`
Mathematics Olympiad, Oude Molen Technical High Scool, Cape Town, SA

`2012`
Top 3 Achiever in the Grade, Oude Molen Technical High Scool, Cape Town, SA

## Occupation

`2023`
__Brigham Young University__, Cape Town

- Custodial

`2024`
__Brigham Young University__, Cape Town

- Teaching Assistant(Introduction to Data Base )
- Technology Specialist at Science and Technology and Inovation, BYU-I 


<!-- ### Footer

Last updated: May 2013 -->